-- Create DEPT table
CREATE TABLE DEPT 
(
    DEPTNO NUMBER(2) PRIMARY KEY,
    DNAME  VARCHAR2(14),
    LOC    VARCHAR2(13)
);

-- Create EMP table
CREATE TABLE EMP 
(
    EMPNO    NUMBER(4) PRIMARY KEY,
    ENAME    VARCHAR2(10),
    JOB      VARCHAR2(9),
    MGR      NUMBER(4),
    HIREDATE DATE,
    SAL      NUMBER(7,2),
    COMM     NUMBER(7,2),
    DEPTNO   NUMBER(2),
    FOREIGN KEY (DEPTNO) REFERENCES DEPT(DEPTNO)
);


